---

CSR-R1:
    hostname: 172.16.100.2
    groups:
        - cisco_group
    data:
        interfaces:
            lo0:
                name: lo0
                ip: 1.1.1.1
                mask: 255.255.255.255
            GigabitEthernet2:
                name: GigabitEthernet2
                ip: 10.1.2.1
                mask: 255.255.255.0
        bgp:
            localAsn: 65001
            routerId: 1.1.1.1
            neighbors:
                - address: 3.3.3.3
                  type: "eBGP"
                  remoteAsn: 65003 
                - address: 4.4.4.4
                  type: "eBGP"
                  remoteAsn: 65004
CSR-R2:
    hostname: 172.16.100.6
    groups:
        - cisco_group
    data:
        interfaces:
            lo0:
                name: lo0
                ip: 2.2.2.2
                mask: 255.255.255.255
            GigabitEthernet2:
                name: GigabitEthernet2
                ip: 10.1.2.2
                mask: 255.255.255.0
        bgp:
            localAsn: 65001
            routerId: 2.2.2.2
            neighbors:
                - address: 3.3.3.3
                  type: "eBGP"
                  remoteAsn: 65003 
                - address: 4.4.4.4
                  type: "eBGP"
                  remoteAsn: 65004
